package responder.prototype.listener;
import net.dv8tion.jda.api.entities.User;
import net.dv8tion.jda.api.entities.channel.middleman.MessageChannel;
import net.dv8tion.jda.api.events.message.MessageReceivedEvent;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;
import org.mockito.junit.jupiter.MockitoExtension;


import static org.junit.jupiter.api.Assertions.*;
import static org.mockito.Mockito.*;

@ExtendWith(MockitoExtension.class)
class InsultGeneratorTest{

    @Test
    public void botIgnoredTest() { //wait until a message is sent on discord

        MessageReceivedEvent event = mock(MessageReceivedEvent.class); //mocking the event object
        User user = mock(User.class); // mocking the user object
        when(user.isBot()).thenReturn(true); // setting up what each method should return
        when(event.getAuthor()).thenReturn(user);

        //ignore bot messages?
        //do not respond to other bots
        if (event.getAuthor().isBot()) {
            assertTrue(event.getAuthor().isBot());
            //
        }
    }
    @Test
    public void doNotIgnoreUsers() { //Does the bot acknowledge users beside bots

        MessageReceivedEvent event = mock(MessageReceivedEvent.class); //mocking the event object
        User user = mock(User.class); // mocking the user object
        when(user.isBot()).thenReturn(true); // setting up what each method should return
        when(event.getAuthor()).thenReturn(user);

        //when the vent is not generated by a bot
        if (!(event.getAuthor().isBot())) {
            assertFalse(event.getAuthor().isBot());
            //
        }
    }

    @Test
    public void canReadUserMessages() { //Does the bot actually read user input?

        MessageReceivedEvent event = mock(MessageReceivedEvent.class); //mocking the event object
        User user = mock(User.class); // mocking the user object
        when(user.isBot()).thenReturn(true); // setting up what each method should return
        when(event.getAuthor()).thenReturn(user);

        //acknowledge user messages and print them to console
        while (!(event.getAuthor().isBot())) {
            try {
                wait();
                String content = event.getMessage().getContentRaw();
                System.out.println(content);
                Boolean userSaidSomething= true;

                if(!(content.isEmpty())){
                    assertTrue(userSaidSomething);
                }

            } catch (InterruptedException e) {
                Thread.currentThread().interrupt();
                System.err.println("Thread Interrupted");
            }

            }
        }

    @Test
    public void onExclamation() { //Does the bot respond with an exclamation mark

        MessageReceivedEvent event = mock(MessageReceivedEvent.class); //mocking the event object
        MessageChannel channel = mock(MessageChannel.class); //mocking the channel object
        User user = mock(User.class); // mocking the user object
        when(user.isBot()).thenReturn(true); // setting up what each method should return
        when(event.getAuthor()).thenReturn(user);

        //acknowledge user messages and print them to console
        while (!(event.getAuthor().isBot())) {
            try {
                wait();
                String content = event.getMessage().getContentRaw();
                Boolean botsaid= true;

                if(content.equals("!")){ //if user sends an "!"
                    String botMessage = channel.sendMessage("I can't hear ye! Scream a bit louder ye old salt!").getContent(); //this is bot response
                    if(!botMessage.isEmpty()){
                        assertTrue(botsaid);
                    }
                }

            } catch (InterruptedException e) {
                Thread.currentThread().interrupt();
                System.err.println("Thread Interrupted");
            }

        }
    }
    @Test
    public void onTry() { //Does the bot respond with an exclamation mark

        MessageReceivedEvent event = mock(MessageReceivedEvent.class); //mocking the event object
        MessageChannel channel = mock(MessageChannel.class); //mocking the channel object
        User user = mock(User.class); // mocking the user object
        when(user.isBot()).thenReturn(true); // setting up what each method should return
        when(event.getAuthor()).thenReturn(user);

        //acknowledge user messages and print them to console
        while (!(event.getAuthor().isBot())) {
            try {
                wait();
                String content = event.getMessage().getContentRaw();
                Boolean botsaid= true;

                if(content.contains("try")){ //if user sends a "try"
                    String botMessage = channel.sendMessage("You Crusty Nut Explorer!").getContent(); //this is bot response
                    if(!botMessage.isEmpty()){
                        assertTrue(botsaid);
                    }
                }

            } catch (InterruptedException e) {
                Thread.currentThread().interrupt();
                System.err.println("Thread Interrupted");
            }

        }
    }
    @Test
    public void onPull() { //Does the bot respond with an exclamation mark

        MessageReceivedEvent event = mock(MessageReceivedEvent.class); //mocking the event object
        MessageChannel channel = mock(MessageChannel.class); //mocking the channel object
        User user = mock(User.class); // mocking the user object
        when(user.isBot()).thenReturn(true); // setting up what each method should return
        when(event.getAuthor()).thenReturn(user);

        //acknowledge user messages and print them to console
        while (!(event.getAuthor().isBot())) {
            try {
                wait();
                String content = event.getMessage().getContentRaw();
                Boolean botsaid= true;

                if(content.contains("pull")){ //if user sends a "pull"
                    String botMessage = channel.sendMessage("Pull harder, You Silly Wiener Wizard!").getContent(); //this is bot response
                    if(!botMessage.isEmpty()){
                        assertTrue(botsaid);
                    }
                }

            } catch (InterruptedException e) {
                Thread.currentThread().interrupt();
                System.err.println("Thread Interrupted");
            }

        }
    }
    @Test
    public void onMd() { //Does the bot respond with an exclamation mark

        MessageReceivedEvent event = mock(MessageReceivedEvent.class); //mocking the event object
        MessageChannel channel = mock(MessageChannel.class); //mocking the channel object
        User user = mock(User.class); // mocking the user object
        when(user.isBot()).thenReturn(true); // setting up what each method should return
        when(event.getAuthor()).thenReturn(user);

        //acknowledge user messages and print them to console
        while (!(event.getAuthor().isBot())) {
            try {
                wait();
                String content = event.getMessage().getContentRaw();
                Boolean botsaid= true;

                if(content.contains("md")){ //if user sends an "md"
                    String botMessage = channel.sendMessage("Ok nut doctor!").getContent(); //this is bot response
                    if(!botMessage.isEmpty()){
                        assertTrue(botsaid);
                    }
                }

            } catch (InterruptedException e) {
                Thread.currentThread().interrupt();
                System.err.println("Thread Interrupted");
            }

        }
    }
    @Test
    public void onRequest() { //Does the bot respond with an exclamation mark

        MessageReceivedEvent event = mock(MessageReceivedEvent.class); //mocking the event object
        MessageChannel channel = mock(MessageChannel.class); //mocking the channel object
        User user = mock(User.class); // mocking the user object
        when(user.isBot()).thenReturn(true); // setting up what each method should return
        when(event.getAuthor()).thenReturn(user);

        //acknowledge user messages and print them to console
        while (!(event.getAuthor().isBot())) {
            try {
                wait();
                String content = event.getMessage().getContentRaw();
                Boolean botsaid= true;

                if(content.contains("request")){ //if user sends a "request"
                    String botMessage = channel.sendMessage("You are a request and I will not merge you").getContent(); //this is bot response
                    if(!botMessage.isEmpty()){
                        assertTrue(botsaid);
                    }
                }

            } catch (InterruptedException e) {
                Thread.currentThread().interrupt();
                System.err.println("Thread Interrupted");
            }

        }
    }

}


